RentQ3/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers
from rest_framework.authtoken.views import obtain_auth_token
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler400, handler500

from crm import views
from schedule.views import UnitViewSet, AppointmentViewSet

router = routers.DefaultRouter()
router.register(r'unit', UnitViewSet)
router.register(r'appointment', AppointmentViewSet)

urlpatterns = [
    path('', views.IndexView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('', include("crm.urls", namespace="crm")),
    path('calendar/', include('schedule.urls')),
    path('accounts/', include("accounts.urls", namespace="accounts")),

    path('api-auth/', include('rest_framework.urls')),
    path('api/', include(router.urls)),
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('api-token-auth/', obtain_auth_token)
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# handler404 = 'crm.views.error_404_view'

handler404 = 'crm.views.handler404'
handler500 = 'crm.views.handler500'

accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from accounts import views
from django.urls import reverse_lazy

app_name = 'accounts'

urlpatterns = [
    path('login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='logout'),
    path('signup/staff/', views.StaffSignUpView.as_view(), name='staff_signup'),
    path('signup/manager/', views.ManagerSignUpView.as_view(), name='manager_signup'),

    path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password_reset/', auth_views.PasswordResetView.as_view(success_url = reverse_lazy('accounts:password_reset_done')), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(success_url = reverse_lazy('accounts:password_reset_complete')), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('user/<int:pk>/settings/time_parameters/', views.TimeParametersUpdateView.as_view(), name='time_parameters')
]

crm/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

from crm import views

app_name = 'crm'

urlpatterns = [
    path('properties/', views.UnitListView.as_view(), name='unit_list'),
    path('properties/new/', views.UnitCreateView.as_view(), name='unit_new'),
    path('properties/<int:pk>/edit', views.UnitUpdateView.as_view(), name='unit_edit'),
    path('properties/<int:pk>/delete', views.UnitDeleteView.as_view(), name='unit_delete'),
    path('properties/<int:pk>/clone', views.clone_unit, name='unit_clone'),
    path('unit/<int:pk>/', views.UnitCalendarView, name='unit_calendar'),
    # path('properties/<int:pk>/calendar', views.PropertyCalendarView.as_view(), name='property_calendar'),

    path('staff/', views.StaffListView.as_view(), name='staff_list'),
    path('staff/<int:pk>/edit', views.StaffUpdateView.as_view(), name='staff_edit'),
    path('staff/<int:pk>/delete', views.StaffDeleteView.as_view(), name='staff_delete'),
    path('staff/<int:pk>/profile', views.StaffProfileView.as_view(), name="staff_profile"),

    path('settings/', views.SettingsListView.as_view(), name="settings_list"),
    path('settings/manager/<int:pk>/profile', views.ManagerProfileView.as_view(), name="manager_profile"),
    path('settings/instructions', views.InstructionsListView.as_view(), name="instructions_list"),
    path('settings/instructions/new', views.InstructionCreateView.as_view(), name="instruction_new"),
    path('settings/instructions/<int:pk>/edit', views.InstructionView.as_view(), name="instruction_edit"),
    path('settings/instructions/<int:pk>/delete', views.InstructionDeleteView.as_view(), name="instruction_delete"),

    path('prospects/<int:pk>/profile', views.ProspectProfileView.as_view(), name='prospect_profile'),
    path('prospects/', views.ProspectListView.as_view(), name='prospect_list')

]

schedule/urls.py
from django.urls import path
from schedule import views

app_name = 'schedule'

urlpatterns = [
    path('', views.CalendarView.as_view(), name='calendar'),
    path('availability/new/', views.AvailabilityCreateView.as_view(), name='availability_new'),
    path('availability/<int:pk>/edit/', views.AvailabilityUpdateView.as_view(), name='availability_edit'),
    path('availability/<int:pk>/delete/', views.AvailabilityDeleteView.as_view(), name='availability_delete'),
    path('appointments/', views.AppointmentListView.as_view(), name='appointment_list'),
    path('appointments/<int:pk>/cancel/', views.AppointmentDeleteView.as_view(), name='appointment_delete'),
    path('appointments/<int:pk>/update/', views.AppointmentUpdateView.as_view(), name='appointment_update'),
    path('appointments/cancelled/', views.AppointmentDeleteConfirmedView.as_view(), name='appointment_delete_confirmed'),
    path('status/<int:pk>/', views.rsvp, name='rsvp'),
    path('appointments/<int:pk>/reminder/', views.send_reminder, name='reminder_send'),
    path('appointments/<int:pk>/rsvp/', views.send_rsvp, name='rsvp_send'),
]

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDHWPdPN-MuSCn3s2lEiCYgs8pHVOJj0Vg&libraries=places&language=en"></script>
    <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script> -->
    <script src="{% static 'js/map.js' %}"></script>
    <script src="{% static 'registration/js/registration.js' %}"></script>
    <script src="{% static 'crm/js/crm.js' %}"></script>  
    <link rel="stylesheet" href="{% static 'css/master.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">
    <link rel="stylesheet" href="{% static 'css/schedule/css/style.css' %}">
    <title></title>
  </head>
  <body>
    <div class="" style="text-align:center">
          </div>
          <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">RentQ</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'home'%}">Home <span class="sr-only">(current)</span></a>
            </li>
            {% if user.is_authenticated%}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'schedule:appointment_list' %}">Appointments</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'schedule:calendar' %}">My Calendar</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'crm:unit_list' %}">My properties</a>
            </li>
            {% endif %}
            {% if user.is_authenticated and user.is_manager %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'crm:staff_list' %}">My staff</a>
            </li>
            {% endif %}
            {% if user.is_authenticated%}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'crm:prospect_list' %}">Prospects</a>
            </li>
            {% endif %}
            <div style="display:flex; position: absolute; right:20px;">

                  {% if user.is_authenticated %}
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'crm:staff_profile' pk=user.pk %}">Welcome, <strong>{{user.get_username}}</strong>!</a>
                  </li>
                      {% if user.is_manager %}
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'crm:settings_list' %}">Settings</a>
                      </li>
                      {% endif %}
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:logout'%}">Logout</a>
                  </li>
                  {% else %}
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:user_login'%}">Login</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:manager_signup'%}">Sign Up</a>
                  </li>
                  {% endif %}
            </div>

          </ul>
        </div>
      </nav>
    {% block body_block %}
    <!-- ####### THIS IS WHERE INHERITANCE TAGS WILL GO #### -->
    {% endblock %}

  </body>
</html>