RentQ3/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers
from rest_framework.authtoken.views import obtain_auth_token
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler400, handler500

from crm import views
from schedule.views import UnitViewSet, AppointmentViewSet

router = routers.DefaultRouter()
router.register(r'unit', UnitViewSet)
router.register(r'appointment', AppointmentViewSet)

urlpatterns = [
    path('', views.IndexView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('', include("crm.urls", namespace="crm")),
    path('calendar/', include('schedule.urls')),
    path('accounts/', include("accounts.urls", namespace="accounts")),

    path('api-auth/', include('rest_framework.urls')),
    path('api/', include(router.urls)),
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('api-token-auth/', obtain_auth_token)
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# handler404 = 'crm.views.error_404_view'

handler404 = 'crm.views.handler404'
handler500 = 'crm.views.handler500'

crm/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

from crm import views

app_name = 'crm'

urlpatterns = [
    path('properties/', views.UnitListView.as_view(), name='unit_list'),
    path('properties/new/', views.UnitCreateView.as_view(), name='unit_new'),
    path('properties/<int:pk>/edit', views.UnitUpdateView.as_view(), name='unit_edit'),
    path('properties/<int:pk>/delete', views.UnitDeleteView.as_view(), name='unit_delete'),
    path('properties/<int:pk>/clone', views.clone_unit, name='unit_clone'),
    path('unit/<int:pk>/', views.UnitCalendarView, name='unit_calendar'),
    # path('properties/<int:pk>/calendar', views.PropertyCalendarView.as_view(), name='property_calendar'),

    path('staff/', views.StaffListView.as_view(), name='staff_list'),
    path('staff/<int:pk>/edit', views.StaffUpdateView.as_view(), name='staff_edit'),
    path('staff/<int:pk>/delete', views.StaffDeleteView.as_view(), name='staff_delete'),
    path('staff/<int:pk>/profile', views.StaffProfileView.as_view(), name="staff_profile"),

    path('settings/', views.SettingsListView.as_view(), name="settings_list"),
    path('settings/manager/<int:pk>/profile', views.ManagerProfileView.as_view(), name="manager_profile"),
    path('settings/instructions', views.InstructionsListView.as_view(), name="instructions_list"),
    path('settings/instructions/new', views.InstructionCreateView.as_view(), name="instruction_new"),
    path('settings/instructions/<int:pk>/edit', views.InstructionView.as_view(), name="instruction_edit"),
    path('settings/instructions/<int:pk>/delete', views.InstructionDeleteView.as_view(), name="instruction_delete"),

    path('prospects/<int:pk>/profile', views.ProspectProfileView.as_view(), name='prospect_profile'),
    path('prospects/', views.ProspectListView.as_view(), name='prospect_list')

]

schedule/urls.py
from django.urls import path
from schedule import views

app_name = 'schedule'

urlpatterns = [
    path('', views.CalendarView.as_view(), name='calendar'),
    path('availability/new/', views.AvailabilityCreateView.as_view(), name='availability_new'),
    path('availability/<int:pk>/edit/', views.AvailabilityUpdateView.as_view(), name='availability_edit'),
    path('availability/<int:pk>/delete/', views.AvailabilityDeleteView.as_view(), name='availability_delete'),
    path('appointments/', views.AppointmentListView.as_view(), name='appointment_list'),
    path('appointments/<int:pk>/cancel/', views.AppointmentDeleteView.as_view(), name='appointment_delete'),
    path('appointments/<int:pk>/update/', views.AppointmentUpdateView.as_view(), name='appointment_update'),
    path('appointments/cancelled/', views.AppointmentDeleteConfirmedView.as_view(), name='appointment_delete_confirmed'),
    path('status/<int:pk>/', views.rsvp, name='rsvp'),
    path('appointments/<int:pk>/reminder/', views.send_reminder, name='reminder_send'),
    path('appointments/<int:pk>/rsvp/', views.send_rsvp, name='rsvp_send'),
]

schedule/models.py
from django.db import models
from django.urls import reverse
from accounts.models import User
from crm.models import Manager, Staff, Unit, Prospect

##Task Model
from django.utils.translation import ugettext_lazy as _
import jsonfield



class Availability(models.Model):
    staff = models.ForeignKey(Staff, on_delete=models.CASCADE)
    unit = models.ManyToManyField('crm.Unit')
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()

    class Meta:
        verbose_name_plural = "Availabilities"
        ordering = ('start_time', )

    def get_absolute_url(self):
        return reverse('schedule:calendar')

    def __str__ (self):
        return "{:d}:{:02d}".format(self.start_time.hour, self.start_time.minute) + " - " + "{:d}:{:02d}".format(self.end_time.hour, self.end_time.minute)

    @property
    def get_html_url(self):
        url = reverse('schedule:availability_edit', args=(self.id,))
        return f'<a href="{url}"> {self.staff} · {"{:d}:{:02d}".format(self.start_time.hour, self.start_time.minute) + " - " + "{:d}:{:02d}".format(self.end_time.hour, self.end_time.minute)} </a>'

    @property
    def is_super_staff(self):
        # import pdb; pdb.set_trace()
        if Unit.objects.filter(staff=self.staff).count() > 1:
            return "Superstaff"
        else:
            return "Staff"


class Appointment(models.Model):

    APPOINTMENT_TYPE_CHOICES = (
        ('zoom', 'Zoom'),
        ('in_person', 'In person'),
    )

    appointment_time = models.DateTimeField()
    unit = models.ForeignKey(Unit, on_delete=models.CASCADE)
    staff = models.ForeignKey(Staff, on_delete=models.CASCADE)
    prospect = models.ForeignKey(Prospect, on_delete=models.CASCADE)
    appointment_type = models.CharField(max_length=40, choices=APPOINTMENT_TYPE_CHOICES, default='in_person')
    status = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse('schedule:appointment_list')

class TaskHistory(models.Model):
    # Relations
    # Attributes - mandatory
    task_name = models.CharField(
        max_length=100,
        verbose_name=_("Task name"),
        help_text=_("Select a task to record"),
        )
    # Attributes - optional
    history = jsonfield.JSONField(
        default={},
        verbose_name=_("history"),
        help_text=_("JSON containing the tasks history")
        )
    # Manager
    # Functions

    # Meta & unicode
    class Meta:
        verbose_name = _('Task History')
        verbose_name_plural = _('Task Histories')

    def __unicode__(self):
        return _("Task History of Task: %s") % self.task_name
    

crm/views.py
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.shortcuts import redirect
from django.views.generic import CreateView, TemplateView, CreateView, UpdateView, DeleteView
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.db.models import Q
from django.template import RequestContext


from crm.forms import UnitForm, StaffForm, ManagerProfileForm, StaffProfileForm, InstructionForm
from crm.models import Unit, Staff, Manager, Prospect, Instruction
from accounts.models import User
from accounts.forms import StaffSignUpForm, ManagerSignUpForm

# Create your views here.



class IndexView(TemplateView):
    template_name = 'crm/index.html'

######## EXCEPTIONS ########

def handler404(request, exception, template_name="crm/404.html"):
    response = render(request,template_name)
    response.status_code = 404
    return response

def handler500(request, template_name="crm/500.html"):
    response = render(request,template_name)
    response.status_code = 500
    return response

######## UNITS ########

class UnitListView(TemplateView):
    template_name = 'crm/unit_list.html'

    def get_context_data(self, **kwargs):
        user = self.request.user
        if user.is_manager:
            kwargs['units'] = Unit.objects.filter(manager=user.id)
        else:
            kwargs['units'] = Unit.objects.filter(staff__user_id=user.id)
        return super().get_context_data(**kwargs)

class UnitCreateView(CreateView):
    template_name = 'crm/unit_form.html'
    form_class = UnitForm
    model = Unit

    ## Add a kwarg 'user' (active user) to the form's kwargs. This user (ie, manager)
    ## is used to filter and display only his agents in the MultiSelect
    def get_form_kwargs(self):
        kwargs = super(UnitCreateView, self).get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs

    ## Set default value of manager to active user when creating new unit
    def form_valid(self, form):
        # import pdb; pdb.set_trace()
        user=self.request.user
        form.instance.manager = Manager.objects.get(user=user)
        return super(UnitCreateView, self).form_valid(form)

class UnitUpdateView(UpdateView):
    template_name = 'crm/unit_form.html'
    form_class = UnitForm
    model = Unit

    ## Add a kwarg 'user' (active user) to the form's kwargs. This user (ie, manager)
    ## is used to filter and display only his agents in the MultiSelect
    def get_form_kwargs(self):
        # import pdb; pdb.set_trace()
        kwargs = super(UnitUpdateView, self).get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs

    def get_context_data(self, **kwargs):
        kwargs['zoomEnabled'] = self.object.manager.zoom_meeting_room != ''
        return super().get_context_data(**kwargs)

class UnitDeleteView(DeleteView):
    template_name = 'crm/unit_confirm_delete.html'
    model = Unit
    success_url = reverse_lazy('crm:unit_list')

def clone_unit(request, pk):
    clone = Unit.objects.get(id=pk)
    clone.pk = None
    clone.save()
    # return render (request,'crm/unit_list.html')
    return redirect('/properties/')

def UnitCalendarView(request, pk):
    return render (request,'rentq/index.html')


######## STAFF ########

class StaffListView(TemplateView):
    template_name = 'crm/staff_list.html'

    def get_context_data(self, **kwargs):
        user = self.request.user.id
        kwargs['staff'] = Staff.objects.filter(manager=user)
        return super().get_context_data(**kwargs)


class StaffUpdateView(UpdateView):
    template_name = "registration/staff_update_form.html"
    model = Staff
    form_class = StaffForm

    def get_context_data(self, **kwargs):
        # import pdb; pdb.set_trace()
        user = self.get_object()
        kwargs['staff'] = Staff.objects.get(user_id=user)
        return super().get_context_data(**kwargs)

    ## Send Active User ID to the form's __init__ method
    def get_form_kwargs(self):
        kwargs = super(StaffUpdateView, self).get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs

class StaffDeleteView(DeleteView):
    template_name = 'crm/staff_confirm_delete.html'
    model = User
    success_url = reverse_lazy('crm:staff_list')

class StaffProfileView(UpdateView):
    template_name = "crm/staff_profile_form.html"
    model = Staff
    form_class = StaffProfileForm


######## PROSPECT ########

class ProspectListView(TemplateView):
    template_name = 'crm/prospect_list.html'

    def get_context_data(self, **kwargs):
        # import pdb; pdb.set_trace()
        user = self.request.user
        if user.is_manager:
            kwargs['prospects'] = Prospect.objects.filter(appointment__staff__manager__user_id=user.id).distinct()
        else:
            kwargs['prospects'] = Prospect.objects.filter(appointment__staff__user_id=user.id).distinct()
        return super().get_context_data(**kwargs)


class ProspectProfileView(TemplateView):
    template_name = 'crm/prospect_profile.html'

    def get_context_data(self, **kwargs):
        # import pdb; pdb.set_trace()
        prospect = self.kwargs['pk']
        user = self.request.user
        kwargs['prospect'] = Prospect.objects.get(id=prospect)
        if user.is_manager:
            kwargs['units_seen'] = Unit.objects.filter(Q(appointment__prospect_id=prospect) & Q(manager_id=user.id)).distinct()
        else:
            kwargs['units_seen'] = Unit.objects.filter(Q(appointment__prospect_id=prospect) & Q(manager_id=Manager.objects.filter(staff=user.id)[0].user_id)).distinct()
        return super().get_context_data(**kwargs)


######## SETTINGS ########

class SettingsListView(TemplateView):
    template_name = 'crm/settings.html'

class ManagerProfileView(UpdateView):
    template_name = "crm/manager_profile_form.html"
    model = Manager
    form_class = ManagerProfileForm

class InstructionsListView(TemplateView):
    template_name = 'crm/instructions.html'

    def get_context_data(self, **kwargs):
        kwargs['instructions'] = Instruction.objects.all()
        return super().get_context_data(**kwargs)

class InstructionView(UpdateView):
    template_name = "crm/instruction_form.html"
    model = Instruction
    form_class = InstructionForm

class InstructionDeleteView(DeleteView):
    template_name = 'crm/instruction_confirm_delete.html'
    model = Instruction
    success_url = reverse_lazy('crm:instructions_list')

class InstructionCreateView(CreateView):
    template_name = "crm/instruction_form.html"
    model = Instruction
    form_class = InstructionForm







######## AVAILABILITY ########

# class AvailabilityCreateView(CreateView):
#     template_name = 'crm/availability_form.html'
#     form_class = AvailabilityForm
#     model = Availability
#
# class AvailabilityUpdateView(UpdateView):
#     template_name = 'crm/availability_form.html'
#     form_class = AvailabilityForm
#     model = Availability
#     pk_url_kwarg = 'pk_alt'
#
#
# class AvailabilityDeleteView(DeleteView):
#     template_name = 'crm/availability_confirm_delete.html'
#     model = Availability
#     success_url = reverse_lazy('crm:staff_list')
#     pk_url_kwarg = 'pk_alt'
#
# class AvailabilityListView(TemplateView):
#     template_name = 'crm/availability_list.html'
#
#     def get_context_data(self, **kwargs):
#         # import pdb; pdb.set_trace()
#         user = self.request.user
#         kwargs['availabilities'] = Availability.objects.filter(staff__manager=Manager.objects.get(user=user)).filter(staff=self.kwargs['pk'])
#         return super().get_context_data(**kwargs)
#

############     FOR STAFF     #########
# class MyCalendarCreateView(CreateView):
#     template_name = 'crm/mycalendar_form.html'
#     form_class = AvailabilityForm
#     model = Availability
#
#     def get_context_data(self, **kwargs):
#
#         context = super().get_context_data(**kwargs)
#         d = self.request.GET
#         context['next_month'] = d
#
#         return context
#
#
# class MyCalendarUpdateView(UpdateView):
#     template_name = 'crm/mycalendar_form.html'
#     form_class = AvailabilityForm
#     model = Availability
#
# class MyCalendarListView(TemplateView):
#     # import pdb; pdb.set_trace()
#     template_name = 'crm/mycalendar_list.html'
#
#     def get_context_data(self, **kwargs):
#         # import pdb; pdb.set_trace()
#         user = self.request.user
#         kwargs['availabilities'] = Availability.objects.filter(staff=user.id)
#         return super().get_context_data(**kwargs)
#
# class MyCalendarDeleteView(DeleteView):
#     template_name = 'crm/mycalendar_confirm_delete.html'
#     model = Availability
#     success_url = reverse_lazy('crm:calendar_list')

templates/crm/availability_confirm_delete.html
{% extends 'base.html' %}

{% block body_block %}
  <div class="container">
    <h1>Delete availability</h1>
    <hr />
    <form method="POST">
      {% csrf_token %}
      <p>Are you sure you want to delete <strong>{{object}}</strong>?</p>
      <input class="btn btn-danger" type="submit" value="Confirm">
      <a class="btn btn-secondary" href="{% url 'crm:availability_list' pk=availability.staff.pk %}">Cancel</a>
    </form>
  </div>

{% endblock %}

templates/crm/availability_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block body_block %}
  <div class="container">
    <h1>
      {% if not form.instance.pk %}
      New availability
      {% else %}
      Update availability
      {% endif %}
    </h1>
    <hr />
    <form class="" method="POST">
      <h1>{{availability.staff.pk}}</h1>
      {% csrf_token %}
      {{form|crispy}}
      <button type="submit" class="btn btn-primary btn-lg">Save</button>
      <a class="btn btn-secondary btn-lg" href="{% url 'crm:availability_list' pk=availability.staff.pk %}">Cancel</a>
    </form>

  </div>

{% endblock %}

templates/crm/availability_list.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load staticfiles %}

{% block body_block %}
  <div class="container">
    <div class="heading">
      <h1>Availability</h1>
      <h2>{{availabilities.staff}}</h2>
      <a class = 'btn btn-primary' href="{% url 'crm:availability_new' %}">+Availability</a>
    </div>
    <hr/>
    {% if availabilities %}
    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Staff</th>
          <th scope="col">Assignment</th>
          <th scope="col">From</th>
          <th scope="col">Until</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        {% for availability in availabilities %}
        <tr>
          <td>{{availability.staff.pk}}</td>
          <td>{{availability.staff}}</td>
          <td>{% for j in availability.unit.all %}
                {{j}},
              {% endfor %}</td>
          <td>{{availability.start}}</td>
          <td>{{availability.end}}</td>
          <td>
            <a href="{% url 'crm:availability_edit' pk_alt=availability.pk pk=availability.staff.pk %}">Edit</a> |
            <a href="{% url 'crm:availability_delete' pk_alt=availability.pk pk=availability.staff.pk %}">Delete</a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    {% else %}
    <p class='empty'>Staff does not have any availability</p>
  {% endif %}
  </div>
{% endblock %}

templates/crm/index.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block body_block %}
  <div class="container">
    {% if user.is_authenticated and user.is_staff %}
      <h1>Welcome, staff!</h1>
    {% elif user.is_authenticated and user.is_manager %}
      <h1>Welcome, manager!</h1>
    {% endif %}
  </div>
{% endblock %}

templates/crm/instruction_confirm_delete.html
{% extends 'base.html' %}
{% block body_block %}
  <div class="container">
    <h1>Delete instruction</h1>
    <hr />
    <form method="POST">
      {% csrf_token %}
      <p>Are you sure you want to delete instruction <strong>{{object.name}}</strong>?</p>
      <input class="btn btn-danger" type="submit" value="Confirm">
      <a class="btn btn-secondary" href="{% url 'crm:instructions_list' %}">Cancel</a>
    </form>
  </div>

{% endblock %}

templates/crm/instruction_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block body_block %}
  <div class="container">
    <h1>
      {% if not form.instance.pk %}
      New Instruction
      {% else %}
      Update Instruction
      {% endif %}
    </h1>
    <hr />
      <form class="form-group" method="POST">
        {% csrf_token %}
        {{form|crispy}}
        <button type="submit" class="btn btn-primary btn-lg">Save</button>
        <a class="btn btn-secondary btn-lg" href="{% url 'crm:instructions_list' %}">Cancel</a>
      </form>
    </div>
  </div>

{% endblock %}

templates/crm/manager_profile_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block body_block %}
  <div class="container">
    <h1>
        Profile
    </h1>
    <hr />
    {% if user.manager.logo %}
        <img src="{{user.manager.logo.url}}" width=50px alt="">
    {% endif %}
    <form class="" enctype="multipart/form-data" method="POST">
      {% csrf_token %}
      {{form.as_p}}
      
      <button type="submit" class="btn btn-primary btn-lg">Save</button>
      <a class="btn btn-secondary" href="{% url 'crm:settings_list' %}">Cancel</a>
    </form>

  </div>

{% endblock %}

templates/crm/mycalendar_confirm_delete.html
{% extends 'base.html' %}
{% block body_block %}
  <div class="container">
    <h1>Delete availability</h1>
    <hr />
    <form method="POST">
      {% csrf_token %}
      <p>Are you sure you want to delete <strong>{{object}}</strong>?</p>
      <input class="btn btn-danger" type="submit" value="Confirm">
      <a class="btn btn-secondary" href="{% url 'crm:my_calendar_list' %}">Cancel</a>
    </form>
  </div>

{% endblock %}

templates/crm/mycalendar_list.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load staticfiles %}


{% block body_block %}
  <div class="container">
    <div class="heading">
      <h1>My calendar</h1>
      <a class = 'btn btn-primary' href="{% url 'crm:my_calendar_new' %}?hello">+New availability</a>
    </div>
    <hr/>

    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Staff</th>
          <th scope="col">Start</th>
          <th scope="col">End</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        {% for availability in availabilities %}
        <tr>
          <td>{{availability.id}}</td>
          <td>{{availability.staff}}</td>
          <td>{{availability.start}}</td>
          <td>{{availability.end}}</td>
          <td>
            <a href="{% url 'crm:my_calendar_edit' pk=availability.pk %}">Edit</a> |
            <a href="{% url 'crm:my_calendar_delete' pk=availability.pk  %}">Delete</a>
          </td>
        </tr>

        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}

templates/crm/prospect_list.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load staticfiles %}


{% block body_block %}
  <div class="container">
    <div class="heading">
      <h1>Prospects</h1>
    </div>
    <hr/>

    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th scope="col">#</th>
          <th scope="col">Name</th>
          <th scope="col">Last Name</th>
          <th scope="col">Email</th>
          <th scope="col">Phone</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        {% for prospect in prospects %}
        <tr>
          <td>{{forloop.counter}}</td>
          <td>{{prospect.first_name}}</td>
          <td>{{prospect.last_name}}</td>
          <td>{{prospect.email}}</td>
          <td>{{prospect.phone}}</td>
          <td class="flex">
            <a class="action" href="{% url 'crm:prospect_profile' pk=prospect.pk %}">View details</a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}

templates/crm/prospect_profile.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% block body_block %}
    <div class="container">
        <div class="heading">
          <h1>{{prospect.first_name}} {{prospect.last_name}}</h1>
        </div>
        <hr/>

        <div>
            <div>
                <h6>Phone:</h6>
                <span>{{prospect.phone}}</span>
            </div>
            <div>
                <h6>Email:</h6>
                {{prospect.email}}
            </div>
            <div>
                <h6>Occupation:</h6>
                {{prospect.occupation}}
            </div>
            <div>
                <h6>Ideal lease term:</h6>
                {{prospect.lease_term}} months
            </div>
            <div>
                <h6>Looking for:</h6>
                {{prospect.unit_size}}
            </div>
            <div>
                <h6>Has seen:</h6>
                {% for j in units_seen %}
                <p>{{j}}</p>
                {% endfor %}
            </div>
        </div>
          




        
      </div>

{% endblock %}

templates/crm/staff_confirm_delete.html
{% extends 'base.html' %}

{% block body_block %}
  <div class="container">
    <h1>Remove agent</h1>
    <hr />
    <form method="POST">
      {% csrf_token %}
      <p>Are you sure you want to remove <strong>{{object}}</strong> from your staff?</p>
      <input class="btn btn-danger" type="submit" value="Confirm">
      <a class="btn btn-secondary" href="{% url 'crm:staff_list' %}">Cancel</a>
    </form>
  </div>

{% endblock %}

templates/crm/staff_profile_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block body_block %}
  <div class="container">
    <h1>
        Profile
    </h1>
    <hr />
    {% if user.staff.profile_pic %}
        <img src="{{user.staff.profile_pic.url}}" width=50px alt="">
    {% endif %}
    <form class="form-group" enctype="multipart/form-data" method="POST">
      {% csrf_token %}
      {{form.profile_pic|as_crispy_field}}
      
      <button type="submit" class="btn btn-primary btn-lg">Save</button>
    </form>

  </div>

{% endblock %}

templates/crm/unit_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block body_block %}
  <div class="container">
    <h1>
      {% if not form.instance.pk %}
      New Property
      {% else %}
      Update Property {{user.manager}}
      {% endif %}
    </h1>
    <hr />
      <div id="map"></div>
      <form class="form-group" method="POST">
        {% csrf_token %}
        {{form|crispy}}

        <button type="submit" class="btn btn-primary btn-lg">Save</button>
        <a class="btn btn-secondary btn-lg" href="{% url 'crm:unit_list' %}">Cancel</a>
      </form>
    </div>
  </div>

{% endblock %}